repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-merge-conflict
    args: [--assume-in-merge]
  - id: mixed-line-ending
    args: [--fix=no]

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
  - id: gitlint-ci
    args: [--debug, --commits, origin/main..HEAD]
